// FALLING LETTERS
export const STRING_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const LETTERS = STRING_LETTERS.split("");

// FALL SPEED
export const FALL_SPEED = "10s";

// FALLING LETTERS INTERVAL
export const FALL_INTERVAL = 500;
